# Use .NET SDK image to build the project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Set working directory
WORKDIR /app

# Copy project file(s) and restore dependencies
COPY ./itu-minitwit/Web/Web/*.csproj ./Web/
COPY ./itu-minitwit/Web/Web.Services/*.csproj ./Web.Services/
COPY ./itu-minitwit/Web/Web.DataAccess/*.csproj ./Web.DataAccess/

COPY ./itu-minitwit/Web/Web ./Web/
COPY ./itu-minitwit/Web/Web.Services ./Web.Services/
COPY ./itu-minitwit/Web/Web.DataAccess ./Web.DataAccess/

WORKDIR /app/Web
RUN dotnet restore --no-cache

# Build and publish the application
RUN dotnet publish -c Release -o /out

# Use .NET runtime image for final container (Sets port to 8080)
FROM mcr.microsoft.com/dotnet/aspnet:8.0

# Install curl
RUN apt update && apt install -y curl

# Set working directory
WORKDIR /itu-minitwit/minitwit.Web

# Copy published files from build stage
COPY --from=build /out ./

# Set environment variable to Production
ENV ASPNETCORE_ENVIRONMENT=Production

# Set entrypoint to run the app
ENTRYPOINT ["dotnet", "Web.dll"]
