$ip_file = "db_ip.txt"

Vagrant.configure("2") do |config|
  config.vm.box = 'digital_ocean'
  config.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
  config.ssh.private_key_path = '~/.ssh/minitwit_ssh_key'
  config.vm.synced_folder "remote_files", "/minitwit", type: "rsync"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"


  # Application Server Configuration
  config.vm.define "appserver", primary: false do |app_server|
    app_server.vm.provider :digital_ocean do |provider|
      provider.ssh_key_name = ENV["SSH_KEY_NAME"]
      provider.token = ENV["DIGITAL_OCEAN_TOKEN"]
      provider.image = 'ubuntu-22-04-x64'
      provider.region = 'fra1'
      provider.size = 's-1vcpu-1gb'
      provider.privatenetworking = true
    end
  
    app_server.vm.hostname = "appserver"
    
    app_server.vm.provision "shell", inline: 'echo "export DOCKER_USERNAME=' + "'" + ENV["DOCKER_USERNAME"] + "'" + '" >> ~/.bash_profile'
    app_server.vm.provision "shell", inline: 'echo "export DOCKER_PASSWORD=' + "'" + ENV["DOCKER_PASSWORD"] + "'" + '" >> ~/.bash_profile'
    
    app_server.vm.provision "shell", inline: <<-SHELL
      
      
      echo "Updating package lists..."
      sudo apt-get update
      
      sudo killall apt apt-get
      sudo rm /var/lib/dpkg/lock-frontend
      
      sudo apt install sqlite3
      
      sudo apt-get install -y docker.io docker-compose-v2
      sudo systemctl status docker
      
      echo -e "\nOpening port for minitwit ...\n"
      docker run --rm hello-world
      docker rmi hello-world
      
      echo -e "\nOpening port for minitwit ...\n"
      ufw allow 5000 && \
      ufw allow 22/tcp
     
      
      echo -e "\nConfiguring default SSH login directory...\n"
      echo "cd /minitwit" >> ~/.bash_profile  # Set default folder on SSH login
            
      echo "Setting up deployment script permissions..."
      chmod +x /minitwit/deploy.sh
    SHELL
  end
end
